name = "ccom"
main = "worker/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[routes]]
pattern = "ccom.isap.vn"
custom_domain = true

[durable_objects]
bindings = [
  { name = "STORE_CONFIG_DO", class_name = "StoreConfigDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["StoreConfigDurableObject"]

[vars]
ADMIN_PASSWORD = "password"

[observability.logs]
enabled = true